//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrdHolder
    {
        public Nullable<long> OrdId { get; set; }
        public string ItemType { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public long Sn { get; set; }
    
        public virtual tbl_OrdKey tbl_OrdKey { get; set; }
    }
}
